// Auto-generated by openapi-typescript on every CI run; do not edit by hand.
// Last regenerated: never (placeholder until first CI run lands the bot commit).
//
// Source: .github/workflows/openapi-types.yml — boots the FastAPI app,
// fetches /openapi.json, runs `pnpm exec openapi-typescript` against this file.
// See openspec/changes/api-foundation-rfc7807/design.md §D5 for the rationale.

export {};
