"""Protocol declarations for observability dependencies.

Per the slice-2 :class:`Port` contract: each external collaborator that
the observability primitives talk to is declared as a structural
:class:`Protocol`. Tests inject in-memory fakes; production wires real
adapters in subsequent slices (R5 brief synthesis wires Anthropic;
P1 approval-channels wires the Perplexity HTTP client).

Three ports for slice O1:

- :class:`PriceTable` — provider+model → USD per million tokens (input
  / output). Module-level static dict in :mod:`.cost_meter` is the
  default implementation; tests inject a fake to make ``cost_usd``
  arithmetic deterministic.
- :class:`ClockPort` — wraps :func:`time.monotonic` for the
  Perplexity throttle's sliding window. Tests inject a fake clock to
  exercise the 60-second-window eviction without ``asyncio.sleep``.
- :class:`LLMResponse` — minimal Protocol for the structural shape that
  cost-meter callers return. Concrete LLM adapters (Anthropic SDK
  responses, Perplexity HTTP responses) coerce into this shape.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Protocol, runtime_checkable


@runtime_checkable
class PriceTable(Protocol):
    """Provider + model → USD-per-million-tokens lookup.

    The default in-process implementation is a static dict in
    :mod:`.cost_meter`. Tests inject fakes to make cost arithmetic
    deterministic without depending on the real Anthropic / OpenAI
    pricing pages.
    """

    def cost_per_million_input(self, provider: str, model: str) -> Decimal:
        """USD per million input tokens for ``(provider, model)``."""
        ...

    def cost_per_million_output(self, provider: str, model: str) -> Decimal:
        """USD per million output tokens for ``(provider, model)``."""
        ...


@runtime_checkable
class ClockPort(Protocol):
    """Monotonic-clock port — wraps :func:`time.monotonic`.

    The Perplexity throttle uses the monotonic clock to record
    timestamps in its sliding window; injecting a fake lets tests
    advance time without :func:`asyncio.sleep` calls (which would slow
    the suite to a crawl + introduce flake).
    """

    def monotonic(self) -> float:
        """Seconds since an arbitrary fixed point — non-decreasing."""
        ...


@runtime_checkable
class LLMResponse(Protocol):
    """Minimal structural shape that ``@cost_meter``-decorated functions return.

    Concrete adapters (Anthropic SDK Message, OpenAI ChatCompletion)
    project onto this triple. The decorator only consumes these three
    fields; everything else flows through unchanged.
    """

    @property
    def tokens_input(self) -> int:
        """Number of input tokens consumed by the call."""
        ...

    @property
    def tokens_output(self) -> int:
        """Number of output tokens generated by the call."""
        ...

    @property
    def cached(self) -> bool:
        """``True`` iff the provider returned a cached response (Anthropic prompt caching, NFR-I3)."""
        ...


__all__ = [
    "ClockPort",
    "LLMResponse",
    "PriceTable",
]
