"""Pydantic v2 DTOs for the costs / observability API surface.

Per the slice-5 typegen pipeline, every DTO declared here flows into
``packages/shared-types/src/index.ts`` on first push (regenerated by
the ``openapi-types`` workflow). Avoid leaking ORM internals; project
the relevant fields onto explicit models.

Ordering: dependent helper models declared first
(``PerProviderBreakdown``, ``PerModelBreakdown``) so the typed FastAPI
endpoint signatures resolve cleanly.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from iguanatrader.contexts.observability.budget import BudgetStatus


class PerProviderBreakdown(BaseModel):
    """One row in a per-provider USD spend breakdown."""

    model_config = ConfigDict(extra="forbid")

    provider: str
    cost_usd: Decimal
    call_count: int = Field(ge=0)


class PerModelBreakdown(BaseModel):
    """One row in a per-model USD spend breakdown."""

    model_config = ConfigDict(extra="forbid")

    provider: str
    model: str
    cost_usd: Decimal
    call_count: int = Field(ge=0)


class ApiCostEventDTO(BaseModel):
    """Read projection of :class:`ApiCostEvent` for the API surface.

    Matches the ORM column set minus ``metadata_json`` (free-form
    JSON; admin views surface it but the dashboard does not).
    """

    model_config = ConfigDict(extra="forbid")

    id: UUID
    tenant_id: UUID
    provider: str
    model: str
    tokens_input: int = Field(ge=0)
    tokens_output: int = Field(ge=0)
    cost_usd: Decimal
    cached: bool
    correlation_id: str | None = None
    created_at: datetime


class CostSummaryDTO(BaseModel):
    """``GET /api/v1/costs/summary`` response (current month total)."""

    model_config = ConfigDict(extra="forbid")

    tenant_id: UUID
    period_start: datetime
    period_end: datetime
    total_cost_usd: Decimal
    total_calls: int = Field(ge=0)
    cached_calls: int = Field(ge=0)


class CostByProviderDTO(BaseModel):
    """``GET /api/v1/costs/by-provider`` response (current month)."""

    model_config = ConfigDict(extra="forbid")

    tenant_id: UUID
    period_start: datetime
    period_end: datetime
    breakdown: list[PerProviderBreakdown]


class CostPerTradeDTO(BaseModel):
    """``GET /api/v1/costs/per-trade`` response (FR42).

    ``cost_per_trade_usd = total_llm_cost_usd / closed_trades_count``;
    when ``closed_trades_count == 0`` the ratio is ``None`` (operators
    interpret as "not enough trades to compute"). The ``closed_trades_count``
    is sourced from the trading bounded context (slice T1+); slice O1
    reports zero until T1 lands.
    """

    model_config = ConfigDict(extra="forbid")

    tenant_id: UUID
    period_start: datetime
    period_end: datetime
    total_llm_cost_usd: Decimal
    closed_trades_count: int = Field(ge=0)
    cost_per_trade_usd: Decimal | None


class BudgetStateDTO(BaseModel):
    """Read projection of :class:`BudgetState` (slice-O1 internal shape)."""

    model_config = ConfigDict(extra="forbid")

    tenant_id: UUID
    status: BudgetStatus
    percent_used: int = Field(ge=0)
    spent_usd: Decimal
    cap_usd: Decimal
    remaining_usd: Decimal


class CostSnapshotDTO(BaseModel):
    """SSE-friendly projection of :class:`CostSnapshotEvent` (NFR-O4)."""

    model_config = ConfigDict(extra="forbid")

    tenant_id: UUID
    bucket_start: datetime
    bucket_end: datetime
    total_cost_usd: Decimal
    total_calls: int = Field(ge=0)
    cached_calls: int = Field(ge=0)
    by_provider: dict[str, Decimal]
    by_model: dict[str, Decimal]


__all__ = [
    "ApiCostEventDTO",
    "BudgetStateDTO",
    "CostByProviderDTO",
    "CostPerTradeDTO",
    "CostSnapshotDTO",
    "CostSummaryDTO",
    "PerModelBreakdown",
    "PerProviderBreakdown",
]
